---
title: "Amostra de Relatório"
author: "Antonio Henrique Pires dos Santos"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pck, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
library(quanteda)
library(lubridate)
library(scales)
```

## Registro das atividades no Conselho de Segurança das Nações Unidas (CSNU)

```{r prep, echo=FALSE, warning=FALSE, message=FALSE}
load(here("data/unsc_filt_pt.RData"))

unsc_filt_pt <- unsc_filt_pt %>% 
  select(filename, country, spv, date, agenda_item3_pt, text) %>% 
  mutate(date = dmy(date))
```

Na primeira análise, podemos identificar quais os membros que mais discursaram no CSNU no gráfico abaixo:

```{r membros, echo=FALSE, fig.align='center', warning=FALSE, message=FALSE, fig.width=6, fig.height=4}

unsc_filt_pt %>% 
  count(country) %>%
  arrange(desc(n)) %>% 
  slice(1:5) %>% 
  mutate(country = recode(country, "United Kingdom Of Great Britain And Northern Ireland" = "Reino Unido",
                          "United States Of America" = "Estados Unidos",
                          "France" = "França",
                          "Russian Federation" = "Rússia",
                          "UN" = "ONU")) %>% 
  ggplot(aes(reorder(country, n), n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw() +
  labs(x = NULL, 
       y = "Número de Discursos", 
       title = str_wrap("Membros que mais discursaram no Conselho de Segurança das Nações Unidas (1995-2019)", 50)) +
  theme(plot.title = element_text(size=12),
        axis.title.x = element_text(size=10))

```


